name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * 1' # Runs At 00:00 on Monday
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 1
          template: "$emojiKey(✔️) <a href='$url' style='color: #ffffff'><strong>$title</strong></a>"
          feed_list: "https://ciromota.tec.br/rss.xml"

  del_runs:
    name: Delete old workflows
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: ciro-mota/ciro-mota
          retain_days: 10
          keep_minimum_runs: 3
          