name: Delete old workflow runs
on:
  schedule:
    - cron: '1 0 * * 1'
  workflow_dispatch:

jobs:
  del_runs:
    name: Delete old workflows
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: ciro-mota/ciro-mota
          retain_days: 10
          keep_minimum_runs: 3
          